### ISSUE TITLE
Disabling first time experience in CI

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#12195]
What are the recommended steps to disable the first time experience and telemetry in CI? Specifically for GitHub Actions. I've tried using the environment variables suggested in other [issues](#3828) but this has no impact. 

```yml
    - name: Restore
      run: dotnet restore
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
```

This [still produces ](https://github.com/jaredpar/github-actions/runs/808061150?check_suite_focus=true)the first time output when running restore (on all OS):

![image](https://user-images.githubusercontent.com/146967/85756846-06abf780-b6c4-11ea-98ee-c4fa73b47118.png)
