### ISSUE TITLE
dotnet restore very slow  on Azure pipelines

### ISSUE THREAD

**Issue by musmuris** [dotnet/sdk#12445]
This is using an Azure Pipelines hosted agent on `windows-latest`

Trying out Azure Pipelines on one of our simpler projects and the whole build is taking ~2 mins. However it took 42 seconds just to do the dotnet restore step.  In an effort to make this faster I added a cache task but next time, even when the cache restored (in just 7 seconds) it then took 57 seconds to do the restore.

```
- task: Cache@2
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/*.csproj'
    restoreKeys: |
       nuget | "$(Agent.OS)"
       nuget
    path: $(Pipeline.Workspace)/.nuget/packages
  displayName: Cache NuGet packages

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: $(solution)
    feedsToUse: 'select'
    verbosityRestore: 'Normal'
```

It can also massively vary between builds - I have seen one with just 20s but also one at 72s (it's around 40-50 usually).
By contrast if I clean my local repo and try it then it's <10s to complete.

Task log files
[cachedrestore.txt](https://github.com/dotnet/sdk/files/4912250/cachedrestore.txt)
[nocacherestore.txt](https://github.com/dotnet/sdk/files/4912251/nocacherestore.txt)
