### ISSUE TITLE
Report Generator tool not being found on DevOps

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [dotnet/sdk#13107]
I have the following yaml in place
```
trigger:
- azure-pipelines-v2

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: DOCKER

steps:
- script: 'dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.5.8'
  displayName: 'Install Report Tool'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '79f3c258-62f0-41df-9f52-8b916da9e6b8'
  displayName: 'Nuget Restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/API.csproj'
  displayName: 'Buil'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/Tests.Unit.csproj'
    arguments: '--configuration $(BuildConfiguration) --collect "XPlat Code coverage" -- RunConfiguration.DisableAppDomain=true'
    publishTestResults: true
  displayName: 'Run Test'

- task: CmdLine@2
  inputs:
    script: 'reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"'
  displayName: 'Create reports'
```
My pipeline is failing at the last step, always reporting `line 1: reportgenerator: command not found`.

I've checked issues like https://github.com/dotnet/sdk/issues/8999 and https://github.com/dotnet/sdk/issues/9777 and it seems like the same issue, except that im already using different tasks... in fact, one of the tests was to actually to install the tool at the begging...

anyone got any orientation on what to do?
