### ISSUE TITLE
Static Web Assets build error with .net 6 rc1 with .net 5 target

### ISSUE THREAD

**Issue by ErikApption** [dotnet/sdk#21056]
.NET 6 rc1 still breaks our open source AElemental library static web assets. This issue seems similar (or possibly identical?) to #19475 but the class library that fails is targeting .NET 5. I already opened #20008 for preview 7 but the same issue happens with rc1

``
2>C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.5_0.targets(500,5): error : Static web asset 'C:\code\elemental-blazor\Elemental\wwwroot\css\elemental.min.css' has invalid source type ''.
2>Done building project "Elemental.csproj" -- FAILED.
``

Repro:
1. pull https://github.com/apption-oscode/elemental-blazor/tree/develop
2. Use .net SDK 6.0.100-rc.1.21458.32
2. Build solution in visual studio

Build did work with .net 6 preview 6 but breaks with .net 6 preview 7 and rc1.

**Comment by javiercn** [comment]
@ErikApption thanks for contacting us.

There was another issue that one of our tests didn't catch. It's fixed in RC2

**Comment by javiercn** [comment]
@ErikApption try the latest nightly build and let us know if you still run into issues.

**Comment by ErikApption** [comment]
ok so there is a half good news - yes the static asset error disappears with 6.0.100-rc.2.21465.13
but one of our wasm project breaks with 6.0.100-rc.2.21465.13.

I could survive with this nightly build - but is there any way to fix this wasm error and integrate that version in our azure devops yaml pipelines?

```
PS C:\code\elemental-blazor> dotnet build
Microsoft (R) Build Engine version 17.0.0-preview-21460-01+8f208e609 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
C:\code\elemental-blazor\Elemental.Documentation.Wasm\Elemental.Documentation.Wasm.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.Mono.browser-wasm with version (= 6.0.0-rc.2.21460.8) [C:\code\elemental-blazor\Elemental.sln]
C:\code\elemental-blazor\Elemental.Documentation.Wasm\Elemental.Documentation.Wasm.csproj : error NU1102:   - Found 5 version(s) in nuget.org [ Nearest version: 6.0.0-rc.1.21451.13 ] [C:\code\elemental-blazor\Elemental.sln]
C:\code\elemental-blazor\Elemental.Documentation.Wasm\Elemental.Documentation.Wasm.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\code\elemental-blazor\Elemental.sln]
  Failed to restore C:\code\elemental-blazor\Elemental.Documentation.Wasm\Elemental.Documentation.Wasm.csproj (in 745 ms).
  6 of 7 projects are up-to-date for restore.

Build FAILED.
```

**Comment by javiercn** [comment]
@ErikApption that's easy to fix, you are missing a feed I believe.

```
<configuration>
  <packageSources>
    <add key="dotnet6" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by ErikApption** [comment]
Ohhhh sweet
>    0 Error(s)

So last thing, can we run a yaml pipeline in devops with that nighly version? I'm not sure how I would install a nighly sdk using devops

**Comment by javiercn** [comment]
@ErikApption are you using the dotnet install scripts?

**Comment by ErikApption** [comment]
Right now we are using UseDotNet task but if there is a way to integrate the dotnet install - we could do that. I'm not sure how a .net install step would look like in devops.
```
  variables:
    NetCoreVersion: '6.0.100-rc.2.21465.13'
    MSBuildEnableWorkloadResolver: 'false'

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk $(NetCoreVersion)'
    inputs:
      version: '$(NetCoreVersion)'
      includePreviewVersions: true
```
that one doesn't work of course

**Comment by javiercn** [comment]
Something like this should work, however I'm not completely sure as I've mostly copied it from another PR that was running into the same issue, so you might need to adapt your build.

```yaml
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup .NET Core
      run: |
        wget https://dot.net/v1/dotnet-install.sh
        bash ./dotnet-install.sh --channel '6.0' --version '6.0.100-rc.2.21465.13'
```
