### ISSUE TITLE
```dotnet nuget push``` does not accept "*.nupkg" as argument in GH Actions

### ISSUE THREAD

**Issue by LuanRoger** [dotnet/sdk#23459]
### Describe the bug
When trying to push a package (.nupkg) generated by ```dotnet pack```, the command ```dotnet nuget push``` claims that there are no .nupkg files in the current folder, even though it is there. It all happened in a pipiline on GitHub Actions, .NET was installed using the action ```actions/setup-dotnet@v1.9.0```.

### To Reproduce
```yaml
name: Nuget-Deploy

on:
  workflow_dispatch:
  
jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
        
      - name: Build
        run: dotnet build .\GlobalStrings\
        
      - name: Test
        run: dotnet test .\GlobalStrings\ --no-build --verbosity normal
        
        
  
  nuget-deploy:
    runs-on: windows-latest
    environment: prod
    needs: build-test
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 5.0.x
      
      - name: Pack
        run: dotnet pack .\GlobalStrings\ -o out
        
      - name: Go package output directory
        run: |
          cd out
          ls
        
      - name: Release on Nuget
        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.GS_NUGET_KEY }} --source "https://nuget.pkg.github.com/LuanRoger/index.json" --skip-duplicate
```
I ran the command ```ls``` to see if the file was in the same directory as me:
```powershell
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           1/16/2022  8:04 PM          10358 GlobalStrings.0.2.2.nupkg
```

- [Repository](https://github.com/LuanRoger/GlobalStrings)

### Exceptions
```powershell
dotnet nuget push "*.nupkg" --api-key *** --source "https://nuget.pkg.github.com/LuanRoger/index.json" --skip-duplicate
```
error: File does not exist (*.nupkg).
> Error: Process completed with exit code 1.

### Further technical details
```
.NET SDK (reflecting any global.json):
 Version:   5.0.404
 Commit:    72c68b830a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\5.0.404\

Host (useful for support):
  Version: 5.0.13
  Commit:  b3afe99225

.NET SDKs installed:
  5.0.404 [C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.13 [C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\shared\Microsoft.WindowsDesktop.App]
```
