### ISSUE TITLE
Problems in .NET 6 Cross Platform Build for win, linux and mac(x64 & arm64)

### ISSUE THREAD

**Issue by TheDevKnight** [dotnet/sdk#25446]
Hi, 

is it currently possible to setup a crossplatform for an dotnet 6 app that must run on windows (x64), linux (x64) and both macOS (x64, arm64). 

I setup this repo https://github.com/TheDevKnight/CrossPlatformApp with the the following azure pipeline yml

```
trigger: none

# VM Images unter https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
# Runtime Identifier (RID) unter https://docs.microsoft.com/en-us/dotnet/core/rid-catalog
strategy:
  matrix:
    win_x64:
      imageName: 'windows-2022'
      runtime: 'win10-x64'
    linux_x64:
      imageName: 'ubuntu-latest'
      runtime: 'linux-x64'
    macOS_x64:
      imageName: 'macOS-latest'
      runtime: 'osx-x64'
    macOS_arm64:
      imageName: 'macOS-latest'
      runtime: 'osx.11.0-arm64'

pool:
  vmImage: $(imageName)

variables:
  solution: '**/CrossPlatformApp.sln'
  buildConfiguration: 'Release'

steps:

- checkout: self
  lfs: true

# Replace UseDotNet@2 to control the architecture of the sdk 

# - pwsh: "&([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Channel LTS -Architecture x64"
#   displayName: 'Install .NET 6.0 SDK on win10-x64'
#   condition: eq(variables['runtime'], 'win10-x64')

- bash: curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel LTS --architecture x64
  displayName: 'Install .NET 6.0 SDK on macOS_x64' 
  condition: eq(variables['runtime'], 'osx-x64')

- bash: curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel LTS --architecture arm64
  displayName: 'Install .NET 6.0 SDK on macOS_arm64' 
  condition: eq(variables['runtime'], 'osx.11.0-arm64')

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet Tools'

- task: NuGetCommand@2
  displayName: 'Restore Solution'
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build Solution'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: '**/CrossPlatformApp.Test.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "XPlat Code Coverage" --runtime $(runtime)'

- task: PowerShell@2
  displayName: 'Create coverage reports'
  inputs:
    targetType: 'inline'
    script: |
      dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.0.4
     
      reportgenerator `
      "-reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml" `
      "-targetdir:$(Build.SourcesDirectory)/coverlet/reports" `
      -reporttypes:"Cobertura"
      
- task: PublishCodeCoverageResults@1
  displayName: 'Publish coverage reports'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/Cobertura.xml'

- task: PowerShell@2
  displayName: 'Check coverage rate'
  inputs:
    targetType: 'inline'
    script: |
      $xml = [xml](Get-Content "$(System.DefaultWorkingDirectory)/coverlet/reports/Cobertura.xml")
        $lineRateText = ($xml.coverage.attributes | Where-Object Name -eq "line-rate").Value
        $lineRate = [math]::Round($lineRateText -as [double], 4) * 100
        [double]$limit = 10.00
        if ($lineRate -lt $limit) {
          throw "Die minimale Codeabdeckung von $limit% wurde mit $lineRate% nicht erreicht!"
        }
```

The Jobs for win, linux and macOs x64 are succecfull. 
But i get the following error for macOS arm64 

```
##[error]Dotnet command failed with non-zero exit code on the following projects : /Users/runner/work/1/s/CrossPlatformApp.sln
```
 
Is it currently possible to setup a working macOS (VmImage is macOS-latest) build/test for x64 AND arm64?

Regards Henry
