### ISSUE TITLE
dotnet nuget push doesn't push package to Nuget when running in GitHub Workflow

### ISSUE THREAD

**Issue by senketsu03** [dotnet/sdk#32631]
### Describe the bug

I'm trying to push my package to Nuget on deploy stage of GitHub workflow. After creating a `.nupkg` file, I run the following code:

```yaml
    - id: push-nuget-nupkg
      run: |
        foreach($file in (Get-ChildItem "${{ inputs.publish-path }}/" -Recurse -Include *.nupkg))
        {
            dotnet nuget push $file -k ${{ inputs.nuget-token }} -s https://api.nuget.org/v3/index.json  --skip-duplicate
        }
      shell: pwsh
```

However, no matter what I do, I get the error: `error: Source parameter was not specified.`

### To Reproduce

```yaml
name: 'Deploy continious'
description: 'Deploy continious build'
inputs:
  nuget-token:
    description: 'Nuget API key'
    required: true
    type: string
  publish-path:
    description: 'Path to published artifacts'
    required: true
    type: string
    
runs:
  using: "composite"
  steps:
    - id: push-nuget-nupkg
      run: |
        foreach($file in (Get-ChildItem "${{ inputs.publish-path }}/" -Recurse -Include *.nupkg))
        {
            dotnet nuget push $file -k ${{ inputs.nuget-token }} -s https://api.nuget.org/v3/index.json  --skip-duplicate
        }
      shell: pwsh      
```

[Repo](https://github.com/senketsu03/dotnet_gh_deploy/blob/master/.github/actions/deploy-continious/action.yml)

### Exceptions (if any)

```pwsh
error: Source parameter was not specified.
```

[Full log](https://github.com/senketsu03/dotnet_gh_deploy/actions/runs/5010312362/jobs/8980075562)

### Further technical details

```pwsh
.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  [22](https://github.com/senketsu03/dotnet_gh_deploy/actions/runs/5010312362/jobs/8980075562#step:11:24).04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.[30](https://github.com/senketsu03/dotnet_gh_deploy/actions/runs/5010312362/jobs/8980075562#step:11:32)2/
Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17
.NET SDKs installed:
  6.0.[40](https://github.com/senketsu03/dotnet_gh_deploy/actions/runs/5010312362/jobs/8980075562#step:11:42)8 [/usr/share/dotnet/sdk]
  7.0.105 [/usr/share/dotnet/sdk]
  7.0.203 [/usr/share/dotnet/sdk]
  7.0.302 [/usr/share/dotnet/sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Other architectures found:
  None
Environment variables:
  DOTNET_ROOT       [/usr/share/dotnet]
global.json file:
  Not found
Learn more:
  https://aka.ms/dotnet/info
Download .NET:
  https://aka.ms/dotnet/download
```
