### ISSUE TITLE
Container publish changes in DN8.P6 not adequately documented in release notes

### ISSUE THREAD

**Issue by MarkStega** [dotnet/sdk#34272]
### Describe the bug
Container publishing was changed in DN8.P6 and the sole documentation in the release notes say that the default tag is now 'latest'.

### To Reproduce
I have been using the following pattern to tag & publish my containers for Azure deployment:

```
    - name: Publish, tag, and push DS image
      run: |
        dotnet publish ICEBG.Web.DataServices/ICEBG.Web.DataServices.csproj --os linux --arch x64 --configuration Azure -p:PublishProfile=DefaultContainer -p:Version=${{ env.unifiedVersion }} -p:ContainerImageName=${{env.appNameDS}}
        docker tag ${{env.appNameDS}}:${{ env.unifiedVersion }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.appNameDS}}:${{ env.unifiedVersion }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.appNameDS}}:${{ env.unifiedVersion }}
        docker images
```
In P5 and earlier SDKs this resulted in
```
  Building image 'icebg.web.ds.wip' with tags 2023-06-14--19-11-22--WIP on top of base image mcr.microsoft.com/dotnet/aspnet:8.0-preview
  Pushed container 'icebg.web.ds.wip:2023-06-14--19-11-22--WIP' to local registry
The push refers to repository [***/icebg.web.ds.wip]
...
```
In P6 I see
```
  Building image 'icebg.web.ds.wip' with tags latest on top of base image mcr.microsoft.com/dotnet/aspnet:8.0-preview
  Pushed image 'icebg.web.ds.wip:latest' to local registry
Error response from daemon: No such image: icebg.web.ds.wip:2023-07-26--12-05-53--WIP
Error: Process completed with exit code 1.
```
So instead of using the tag generated from the version I am seeing the tag of 'latest'. I need to know how to tag an image with something other than 'latest' as I did in P5 and earlier.

Breaking changes should really be documented in the release notes with more detail.

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by baronfel** [comment]
In the meantime, you should set the following property to tag the image with the version as you used to:

```xml
<ContainerImageTag>$(Version)</ContainerImageTag>
```

This can be specified by command-line flag or project property.

**Comment by MarkStega** [comment]
@baronfel 

Thanks for the update, I know that documentation can be frustrating!

Anyhow, I added the tag specification and still have an issue (and, of course, I may not be understanding something in the flow).

My actions commands are now as follows (The only change is adding the specification of the ContainerImageTag on the 'dotnet publish')
```
    - name: Publish, tag, and push DS image
      run: |
        echo "*** dotnet publish"
        dotnet publish ICEBG.Web.DataServices/ICEBG.Web.DataServices.csproj --os linux --arch x64 --configuration Azure -p:PublishProfile=DefaultContainer -p:Version=${{ env.unifiedVersion }} -p:ContainerRepository=${{env.appNameDS}} -p:ContainerImageTag=${{ env.unifiedVersion }} 
        echo "*** docker tag"
        echo "docker tag ${{env.appNameDS}}:${{ env.unifiedVersion }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.appNameDS}}:${{ env.unifiedVersion }}
        echo "*** docker push"
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.appNameDS}}:${{ env.unifiedVersion }}
        echo "*** show images"
        docker images
```
And the result looks promising with the image that was built having the tag as it did previously
However, the next step in the action (the 'docker tag' step) is now failing
```
  Building image 'icebg.web.ds.wip' with tags 2023-07-26--18-39-35--WIP on top of base image mcr.microsoft.com/dotnet/aspnet:8.0-preview
  Pushed image 'icebg.web.ds.wip:2023-07-26--18-39-35--WIP' to local registry
*** docker tag
Error response from daemon: No such image: icebg.web.ds.wip:2023-07-26--18-39-35--WIP
Error: Process completed with exit code 1.
```
I was never clear on what the 'docker tag' step was doing and the docker docs are less than helpful.

**Comment by MarkStega** [comment]
@baronfel 

I ran the 'dotnet publish' step locally, and followed it with a 'docker images' and see this:
```
C:\Solutions\OHI\ICEBG>docker images
REPOSITORY         TAG       IMAGE ID       CREATED              SIZE
icebg.web.ds.wip   1.1       1d42898aace6   About a minute ago   249MB

C:\Solutions\OHI\ICEBG>
```
I added an additional trace of 'docker images' right after the 'dotnet publish' in the github actions workflow but do not see the repository:
```
ICEBG.Web.DataServices -> /home/runner/work/ICEBG/ICEBG/.artifacts/publish/ICEBG.Web.DataServices/azure_linux-x64/
  Building image 'icebg.web.ds.wip' with tags 2023-07-27--14-02-39--WIP on top of base image mcr.microsoft.com/dotnet/aspnet:8.0-preview
  Pushed image 'icebg.web.ds.wip:2023-07-27--14-02-39--WIP' to local registry
*** show images
REPOSITORY       TAG         IMAGE ID       CREATED        SIZE
node             18          0f9df951673d   7 days ago     1.09GB
node             18-alpine   9[112](https://github.com/MarkStega/ICEBG/actions/runs/5681527489/job/15397912095#step:6:113)cb38e57e   7 days ago     176MB
moby/buildkit    latest      869c7038a926   2 weeks ago    172MB
node             16          81c6e5ef93fc   3 weeks ago    909MB
buildpack-deps   buster      7eb882719b28   3 weeks ago    802MB
buildpack-deps   bullseye    32c83682cfff   3 weeks ago    833MB
debian           10          1de12428f6f4   3 weeks ago    [114](https://github.com/MarkStega/ICEBG/actions/runs/5681527489/job/15397912095#step:6:115)MB
debian           11          189a2f977ff1   3 weeks ago    124MB
ubuntu           20.04       14be0685b768   4 weeks ago    72.8MB
ubuntu           22.04       5a81c4b8502e   4 weeks ago    77.8MB
node             16-alpine   d22e42cbfdbb   5 weeks ago    [118](https://github.com/MarkStega/ICEBG/actions/runs/5681527489/job/15397912095#step:6:119)MB
alpine           3.16        5cb2da5c2391   6 weeks ago    5.54MB
alpine           3.17        1f73a9d63274   6 weeks ago    7.05MB
alpine           3.18        c1aabb73d233   6 weeks ago    7.33MB
ubuntu           18.04       f9a80a55f492   8 weeks ago    63.2MB
node             14          1d12470fa662   3 months ago   912MB
node             14-alpine   0dac3dc27b1a   3 months ago   [119](https://github.com/MarkStega/ICEBG/actions/runs/5681527489/job/15397912095#step:6:120)MB
*** docker tag
Error response from daemon: No such image: icebg.web.ds.wip:2023-07-27--14-02-39--WIP
Error: Process completed with exit code 1.
```

Does this help?

**Comment by baronfel** [comment]
Hey @MarkStega - that's concerning for sure - can you by chance get a binlog from one of these runs? I'm curious to see _which_ container daemon was used here. There was some work done recently to optionally offer support for `podman` if available, and I'm wondering if you're seeing that here/ Does your build server have `podman` installed? If it does can you add a `podman image list --all` to your debugging?

**Comment by MarkStega** [comment]
@baronfel 

I found the destination

On P5 I was seeing "Pushed container 'icebg.web.ds.wip:2023-06-14--19-11-22--WIP' to local registry"

On P6 I see "Pushed image '***/icebg-web-dataservices:2023-07-27--16-35-16--WIP' to registry '***'"

Instead of getting pushed to the local registry the images are getting pushed to my Azure container registry. And since I was not specifying the repository a new repository called 'icebg-web-dataservices' was created.

**Comment by MarkStega** [comment]
@baronfel 

I went back to my original workflow (without the image tag) and discovered that the published image still was getting pushed to my Azure container registry (with the 'latest' tag). So it appears (as of P6) that the github actions behavior is no longer to use the default local registry during a publish if one has a docker login.

I totally missed the one liner in the release notes for DN8.P3 that referred to your blog that showed the support of authentication by the 'dotnet publish'. On reading the article I do see where one can specify the container registry & image name. I really liked the simplified workflow even if I "backed into it" with your help on the tag.

I think that the default of using the remote registry is fine but should probably be mentioned in the release notes.

**Comment by hackf5** [comment]
I can confirm that GitHub's `ubuntu-latest` has `podman` installed and `dotnet publish` in DN8.P6 defaults to `podman`.

![image](https://github.com/dotnet/sdk/assets/48881437/70ce68c7-5001-4e24-8b34-a98dad6080ed)

![image](https://github.com/dotnet/sdk/assets/48881437/b4045ea8-b0dc-472c-b618-bf0a88f6b5bd)

![image](https://github.com/dotnet/sdk/assets/48881437/aa4ad004-8494-467c-b430-8f36695121d6)

I guess this is unintentional and that `Docker` should be the default.

You can force publish to use docker by specifying the command line parameter `-p:LocalRegistry=Docker`

**Comment by baronfel** [comment]
@hackf5 do you have a binlog we could look at here? Docker should be the default, and I've got tests in baronfel/sdk-container-demo that don't show the same change in default.

**Comment by hackf5** [comment]
@baronfel if you can tell me how to create a binlog then i can give it a go. however, i'm not doing anything special. in the following workflow without `-p:LocalRegistry=Docker` it publishes to podman in an `ubuntu` based github action.

```yaml
steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # NuGet requires version without v prefix on .NET Publish
      - name: Set Version from Tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
          dotnet-quality: "preview"

      - name: Restore Periscope Dependencies
        working-directory: ./${{ inputs.repository }}
        run: >
          dotnet restore 
          --runtime linux-x64

      - name: Publish Container to Local Docker
        working-directory: ${{ inputs.publish_path }}
        env:
          ContainerImageTags: "'\"${{ env.VERSION }};latest\"'"
        run: >
          dotnet publish
          --no-restore
          --runtime linux-x64
          --self-contained
          --configuration Release
          -p:PublishProfile=DefaultContainer
          -p:LocalRegistry=Docker
          -p:ContainerRepository=${{ env.ContainerRepository }}
          -p:ContainerImageTags=${{ env.ContainerImageTags }}
          -p:Version=${{ env.VERSION }}
```
