### ISSUE TITLE
staticwebassets.build.json' not found with Pack task for .NET v7.0.400

### ISSUE THREAD

**Issue by pmeems** [dotnet/sdk#34601]
### Describe the bug
We have a .NET7 solution with Blazor components. We want to create a NuGet package and send it to our private feed in our Azure DevOps.
We use a YAML pipeline to 
1. Restore
2. Build
3. Test
4. Pack
5. Publish
6. Push to internal feed

This has worked for weeks.
We use an Agent Pool with 8 agents. Most of them have been upgraded to .NET v7.0.400, just one is still .NET v7.0.306

When the pipeline runs on an upgraded agent I get this error:
`Manifest file at 'obj\Release\net7.0\staticwebassets.build.json' not found.`

When I specifically target the agent with .NET v7.0.306 I have no pack error and everything works as expected.

### To Reproduce

This is my YAML-script:
```
steps:
  - checkout: self
    clean: true
    lfs: true

  - task: UseDotNet@2
    displayName: Downloading .Net 7 SDK
    inputs:
      packageType: "sdk"
      version: "7.0.306"  # Newer versions will not work with pack

  - task: DotNetCoreCLI@2
    displayName: Restore solution
    condition: always()
    inputs:
      command: "restore"
      projects: "$(Build.Repository.LocalPath)/**/*.sln"
      feedsToUse: 'config'
      nugetConfigPath: 'nuget.config' 

  - task: DotNetCoreCLI@2
    displayName: Build solution
    condition: succeeded()
    inputs:
      command: "build"
      projects: "$(Build.Repository.LocalPath)/**/*.sln"
      arguments: '/p:Configuration=${{ parameters.BuildConfiguration }} /p:Version=$(Build.BuildNumber) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Pack Nuget    
    inputs:
      command: 'pack'
      packagesToPack: '**/Blazor.Components.csproj;!**/*Tests.csproj;!**/*.ComponentsAccessibilityTests.csproj'
      configuration: 'Release'
      packDirectory: '$(Build.ArtifactStagingDirectory)/Nuget'
      nobuild: true
      versioningScheme: 'byBuildNumber'
```

This last task fails with the mentioned error about the missing file.

The content of the .csproj file:
```
<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageId>PenR.Blazor.Components</PackageId>
        <Title>PenR Blazor Components</Title>
        <Product>PenR.Blazor.Components</Product>
        <Copyright>RDW</Copyright>
        <Platforms>AnyCPU;x64;x86</Platforms>
        <PlatformTarget>x64</PlatformTarget>
        <StaticWebAssetsEnabled>true</StaticWebAssetsEnabled>
    </PropertyGroup>
    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Meziantou.Analyzer" Version="2.*">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="7.*" />
    </ItemGroup>
</Project>
```

And the contents of the Directory.Build.props:
```
<Project>
  <PropertyGroup>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
  </PropertyGroup>

  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>We</Authors>
    <Company>Us</Company>
    <PackageProjectUrl></PackageProjectUrl>
    <RepositoryUrl>https://dev.azure.com/.../.../_git/Rdw.Blazor.Components</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageIcon>BlazorComponents.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="BlazorComponents.png" Pack="true" PackagePath="\" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
```

### Exceptions (if any)

```
     1>Target "ResolveStaticWebAssetsConfiguration" in file "D:\Data\a9\_tool\dotnet\sdk\7.0.400\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets" from project "D:\Data\a9\216\s\Src\Components\Blazor.Components.csproj" (target "IncludeStaticWebAssetsPackItems" depends on it):
       Task "MakeDir" skipped, due to false condition; (!Exists('$(_StaticWebAssetsManifestBase)')) was evaluated as (!Exists('obj\Release\net7.0\')).
       Task "MakeDir" skipped, due to false condition; (!Exists('$(_StaticWebAssetsIntermediateOutputPath)')) was evaluated as (!Exists('obj\Release\net7.0\staticwebassets\')).
     1>Done building target "ResolveStaticWebAssetsConfiguration" in project "Blazor.Components.csproj".
     1>Target "LoadStaticWebAssetsBuildManifest" in file "D:\Data\a9\_tool\dotnet\sdk\7.0.400\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets" from project "D:\Data\a9\216\s\Src\Components\Blazor.Components.csproj" (target "IncludeStaticWebAssetsPackItems" depends on it):
       Using "ReadStaticWebAssetsManifestFile" task from assembly "D:\Data\a9\_tool\dotnet\sdk\7.0.400\Sdks\Microsoft.NET.Sdk.Razor\targets\..\tasks\net7.0\Microsoft.NET.Sdk.Razor.Tasks.dll".
       Task "ReadStaticWebAssetsManifestFile"
     1>D:\Data\a9\_tool\dotnet\sdk\7.0.400\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(499,5): error : Manifest file at 'obj\Release\net7.0\staticwebassets.build.json' not found. [D:\Data\a9\216\s\Src\Components\Blazor.Components.csproj]
       Done executing task "ReadStaticWebAssetsManifestFile" -- FAILED.
     1>Done building target "LoadStaticWebAssetsBuildManifest" in project "Blazor.Components.csproj" -- FAILED.
     1>Done Building Project "D:\Data\a9\216\s\Src\Components\Blazor.Components.csproj" (pack target(s)) -- FAILED.

Build FAILED.

       "D:\Data\a9\216\s\Src\Components\Blazor.Components.csproj" (pack target) (1) ->
       (LoadStaticWebAssetsBuildManifest target) -> 
         D:\Data\a9\_tool\dotnet\sdk\7.0.400\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(499,5): error : Manifest file at 'obj\Release\net7.0\staticwebassets.build.json' not found. [D:\Data\a9\216\s\Src\Components\Blazor.Components.csproj]
```

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
All agents are Windows agents, only the .NET7 version differs.
Other pipelines which don't create NuGet packages but deploy webapps to Azure have no issues on any of the agents.
