### ISSUE TITLE
after updating to sdk 9.0.100-preview.7.24407.12 build fails with "MSB3030: Could not copy the file...apphost.exe"

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/sdk#42722]
i did bulk update to 9.0.100-preview.7 in global.json files in a number of repos. and no CI is breaking with  "MSB3030: Could not copy the file...apphost.exe"

previous (working) version: 9.0.100-preview.6.24328.19
failing version: 9.0.100-preview.7.24407.12
Build server: AppVeyor
Repository: https://github.com/VerifyTests/Verify.FakeItEasy
Commit that broke it: https://github.com/VerifyTests/Verify.FakeItEasy/commit/5ff97f142f8ef4bbc3d4bf7bfd3ae4a0a59d57c5

Potentially related to https://github.com/dotnet/msbuild/issues/8003

build script:
```
image: Visual Studio 2022
environment:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build_script:
- pwsh: |
    Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
    ./dotnet-install.ps1 -JSonFile src/global.json -Architecture x64 -InstallDir 'C:\Program Files\dotnet'
- dotnet build src --configuration Release
- dotnet test src --configuration Release --no-build --no-restore --filter Category!=Integration
test: off
on_failure:
  - ps: Get-ChildItem *.received.* -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
artifacts:
- path: nugets\*.nupkg
```

build log
```
Build started
git clone -q --branch=main https://github.com/VerifyTests/Verify.FakeItEasy.git C:\projects\verify-fakeiteasy
git checkout -qf 5ff97f142f8ef4bbc3d4bf7bfd3ae4a0a59d57c5
Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
./dotnet-install.ps1 -JSonFile src/global.json -Architecture x64 -InstallDir 'C:\Program Files\dotnet'
dotnet-install: Remote file https://dotnetcli.azureedge.net/dotnet/Sdk/9.0.100-preview.7.24407.12/dotnet-sdk-9.0.100-preview.7.24407.12-win-x64.zip size is 281047975 bytes.
dotnet-install: Downloaded file https://dotnetcli.azureedge.net/dotnet/Sdk/9.0.100-preview.7.24407.12/dotnet-sdk-9.0.100-preview.7.24407.12-win-x64.zip size is 281047975 bytes.
dotnet-install: The remote and local file sizes are equal.
dotnet-install: Extracting the archive.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install/windows#dependencies
dotnet-install: Installed version is 9.0.100-preview.7.24407.12
dotnet-install: Installation finished
dotnet build src --configuration Release
  Determining projects to restore...
  Restored C:\projects\verify-fakeiteasy\src\Tests\Tests.csproj (in 9.9 sec).
  Restored C:\projects\verify-fakeiteasy\src\Verify.FakeItEasy\Verify.FakeItEasy.csproj (in 9.9 sec).
  Verify.FakeItEasy -> C:\projects\verify-fakeiteasy\src\Verify.FakeItEasy\bin\Release\net6.0\Verify.FakeItEasy.dll
  Verify.FakeItEasy -> C:\projects\verify-fakeiteasy\src\Verify.FakeItEasy\bin\Release\net48\Verify.FakeItEasy.dll
  Verify.FakeItEasy -> C:\projects\verify-fakeiteasy\src\Verify.FakeItEasy\bin\Release\net7.0\Verify.FakeItEasy.dll
  Verify.FakeItEasy -> C:\projects\verify-fakeiteasy\src\Verify.FakeItEasy\bin\Release\net8.0\Verify.FakeItEasy.dll
C:\Program Files\dotnet\sdk\9.0.100-preview.7.24407.12\Microsoft.Common.CurrentVersion.targets(5327,5): error MSB3030: Could not copy the file "C:\projects\verify-fakeiteasy\src\Tests\obj\Release\net8.0\apphost.exe" because it was not found. [C:\projects\verify-fakeiteasy\src\Tests\Tests.csproj]
  Successfully created package 'C:\projects\verify-fakeiteasy\src\..\nugets\Verify.FakeItEasy.2.1.0.nupkg'.
Build FAILED.
C:\Program Files\dotnet\sdk\9.0.100-preview.7.24407.12\Microsoft.Common.CurrentVersion.targets(5327,5): error MSB3030: Could not copy the file "C:\projects\verify-fakeiteasy\src\Tests\obj\Release\net8.0\apphost.exe" because it was not found. [C:\projects\verify-fakeiteasy\src\Tests\Tests.csproj]
    0 Warning(s)
    1 Error(s)
Time Elapsed 00:00:49.87
Command exited with code 1
Get-ChildItem *.received.* -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
```
