### ISSUE TITLE
Github action fails trying to load dotnet-runtime-wasm-linux

### ISSUE THREAD

**Issue by hbraasch** [dotnet/sdk#45519]
I've been successfull uploading webassembly apps to Azure Static Web Apps via Github for a while.
I've now, for the first time added the LiveCharts library (livechartscore.skiasharpview.uno.winui) to an application. The app runs fine under wasm (and displaying the graphs) under the debugger.

However, when I upload to GitHub and the Action runs, it build now fails with the following error:

```
Downloading dotnet-runtime-wasm-linux-498e18e-7331dcb60e0-8790049905-Release-simd to /tmp/dotnet-runtime-wasm-linux-498e18e-7331dcb60e0-8790049905-Release-simd.zip
chmod: cannot access '/tmp/dotnet-runtime-wasm-linux-498e18e-7331dcb60e0-8790049905-Release-simd/.lock': No such file or directory
```

I'm using the exact same yml file for all my uploads, this time only the library is added. Do I need to add some instructions to the yml file to correct this? I've got no idea what to do:

Here is the action's yml file:

```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
         dotnet-version: '8.0.x'
      - run: |
          cd UnoChartTester
          dotnet publish -f net8.0-browserwasm -c Release -p:TargetFrameworks=net8.0-browserwasm
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_HILL_04D9D6F10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "UnoChartTester/bin/Release/net8.0-browserwasm/publish/wwwroot" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_HILL_04D9D6F10 }}
          action: "close"
```

Here is a link to a sample application demonstrating the problem:

https://github.com/hbraasch/UnoChartTester.git

Help shall be much appreciated
